<template>
    <div class="media-item card" :class="item.selected ? 'media-item-selected' : ''" >
        <div class="card-image media-icon-container cursor-pointer" @click.exact="select(true)" @click.shift.exact="select(false)">
            <img v-if="item.type === TYPE_IMAGE" :src="'/content/media/' + item.filename" :alt="item.caption ? item.caption : item.name">
            <b-icon icon="file-pdf" size="is-large" class="media-icon" v-else-if="item.type === TYPE_DOCUMENT"></b-icon>
            <b-icon icon="music" size="is-large" class="media-icon" v-else-if="item.type === TYPE_AUDIO"></b-icon>
        </div>
        <div class="card-content">
            <p class="title is-4 cursor-pointer" @click.exact="select(true)" @click.shift.exact="select(false)">{{ item.name }}</p>
            <p class="subtitle is-6 cursor-pointer" v-if="displayFullPath" @click.exact="select(true)" @click.shift.exact="select(false)">
                inside '{{ directoryPath }}'
<!--                <b-icon icon="file-image" v-if="item.type === TYPE_IMAGE"></b-icon>-->
<!--                <b-icon icon="file" v-else-if="item.type === TYPE_DOCUMENT"></b-icon>-->
<!--                <b-icon icon="file-audio" v-else-if="item.type === TYPE_AUDIO"></b-icon>-->
<!--                {{ item.slug }}.{{ item.extension }}-->
            </p>

            <div v-if="item.selected" class="content media-item-toolbar">
                <b-button icon-left="photo-video" size="is-small" rounded tag="a" :href="externalLink">View</b-button>
                <b-button icon-left="pencil-alt" size="is-small" rounded @click="openEditModal">Edit info</b-button>
                <MediaChooseDirectory v-if="!item.deletedAt" @submit="moveToDirectory"></MediaChooseDirectory>
                <b-button v-if="!item.deletedAt" icon-left="share" size="is-small" rounded outlined @click="isShareModalActive = true">Share</b-button>
                <b-button v-if="!item.deletedAt" icon-left="trash" size="is-small" rounded outlined type="is-danger" @click="deleteItem">Delete</b-button>
                <b-button v-if="item.deletedAt" icon-left="recycle" size="is-small" rounded outlined @click="restoreItem">Restore</b-button>
                <b-button v-if="item.deletedAt" icon-left="trash" size="is-small" rounded outlined type="is-danger" @click="confirmForceDeleteItem">Delete forever</b-button>
            </div>
        </div>

        <b-modal :active.sync="isShareModalActive" trap-focus has-modal-card width="80%">
            <div class="modal-card" style="width: auto;">
                <header class="modal-card-head">
                    <p class="modal-card-title">Share a public link</p>
                </header>
                <section class="modal-card-body">
                    <p>When referencing "{{ item.name }}" externally, use the following URL:<br/>
                    <a :href="externalLink">{{ externalLink }}</a>
                    </p>
                    <br />

                    <p>To use this item within Oxygen, use the <em>"Insert Photo or File"</em> button inside the content editor.</p>
                </section>
                <footer class="modal-card-foot is-flex">
                    <div class="is-flex-grow-1"></div>
                    <b-button
                        label="Close"
                        @click="isShareModalActive = false" />
                </footer>
            </div>
        </b-modal>

        <b-modal :active.sync="isEditModalActive" trap-focus has-modal-card width="80%">
            <div class="modal-card" style="width: auto">
                <header class="modal-card-head">
                    <p class="modal-card-title">Edit Media Item - {{ name }}</p>
                </header>
                <section class="modal-card-body">
                    <b-field label="Name">
                        <b-input v-model="name"></b-input>
                    </b-field>
                    <b-field>
                        <template #label>
                            Slug
                            <b-tooltip multilined position="is-right" type="is-dark" label="How this item is referenced in code. If left blank, it will be autogenerated.">
                                <b-icon size="is-small" icon="question-circle"></b-icon>
                            </b-tooltip>
                        </template>
                        <p class="control">
                            <b-tooltip label="To change, move this item to another directory."
                                       multilined
                                       type="is-dark"
                                       position="is-right">
                                <b-button disabled>{{ directorySlug }}/</b-button>
                            </b-tooltip>
                        </p>
                        <b-input v-model="slug" placeholder="will be set from 'Name'" expanded></b-input>
                        <p class="control">
                            <b-tooltip label="The extension is set from the file type."
                                       multilined
                                       type="is-dark"
                                       position="is-left">
                                <b-button disabled>.{{ item.extension }}</b-button>
                            </b-tooltip>
                        </p>
                    </b-field>
                    <b-field label="Author">
                        <b-input v-model="author"></b-input>
                    </b-field>
                    <b-field>
                        <template #label>
                            Caption
                            <b-tooltip multilined position="is-right" type="is-dark" label="May be displayed next to the item, or used as alt-text for vision-impaired.">
                                <b-icon size="is-small" icon="question-circle"></b-icon>
                            </b-tooltip>
                        </template>
                        <b-input v-model="caption"></b-input>
                    </b-field>
                    <b-field>
                        <template #label>
                            Description
                            <b-tooltip multilined position="is-right" type="is-dark" label="Arbitrary extra details/notes - will not be shown to the public.">
                                <b-icon size="is-small" icon="question-circle"></b-icon>
                            </b-tooltip>
                        </template>
                        <b-input v-model="description" type="textarea"></b-input>
                    </b-field>

                    <label class="label">Variants</label>
                    <b-table striped :data="variants">
                        <b-table-column label="Filename" field="filename" v-slot="props"><a :href="'/content/media/' + props.row.filename">{{ props.row.filename }}</a></b-table-column>
                        <b-table-column label="Width (px)" field="width" v-slot="props">{{ props.row.width }}</b-table-column>
                    </b-table>

                    <label class="label">Versions</label>

                    <b-table striped :data="versions"
                             :loading="versions.length === 0"
                             custom-row-key="id"
                             detailed
                             detail-key="id">
                        <b-table-column label="Name" field="name" v-slot="props">{{ props.row.name }}</b-table-column>
                        <b-table-column label="Path" field="fullPath" v-slot="props">{{ props.row.fullPath }}</b-table-column>
                        <b-table-column label="Last Updated" field="updatedAt" v-slot="props">
                            <div class="is-size-7">{{ Internationalize.formatLastUpdated(props.row.updatedAt) }}</div>
                        </b-table-column>

                        <b-table-column label="" v-slot="slotProps">
                            <b-button rounded :disabled="slotProps.row.headVersion === null" @click="restoreVersion(slotProps.row.id)">
                                <span v-if="slotProps.row.headVersion === null">Already current</span>
                                <span v-else>Restore version</span>
                            </b-button>
                        </b-table-column>

                        <template slot="detail" slot-scope="props">
                            <article class="media">
                                <div class="media-content">
                                    <div class="content">
                                        <p>
                                            <strong>Author: </strong><span v-if="props.row.author">{{ props.row.author }}</span><em v-else>none</em><br>
                                            <strong>Caption: </strong><span v-if="props.row.caption">{{ props.row.caption }}</span><em v-else>none</em><br>
                                            <strong>Description: </strong><span v-if="props.row.description">{{ props.row.description }}</span><em v-else>none</em><br>
                                        </p>
                                    </div>
                                </div>
                            </article>
                        </template>
                    </b-table>
                </section>
                <footer class="modal-card-foot is-flex">
                    <div class="is-flex-grow-1"></div>
                    <b-button @click="isEditModalActive = false">Close</b-button>
                    <b-button @click="saveEdits" type="is-primary">Save</b-button>
                </footer>
            </div>
        </b-modal>
    </div>
</template>

<script>

import {morphToNotification} from "../api";
import MediaApi from "../MediaApi";
import MediaChooseDirectory from "./MediaChooseDirectory.vue";
import Internationalize from "../Internationalize";
import {getDirectoryFullSlug, getDirectoryPathString} from "../MediaDirectoryApi";

const TYPE_IMAGE = 0;
const TYPE_DOCUMENT = 1;
const TYPE_AUDIO = 2;

export default {
    name: "MediaItem.vue",
    components: {MediaChooseDirectory},
    props: {
        item: Object,
        displayFullPath: Boolean
    },
    data() {
        return {
            TYPE_IMAGE: TYPE_IMAGE,
            TYPE_AUDIO: TYPE_AUDIO,
            TYPE_DOCUMENT: TYPE_DOCUMENT,
            isEditModalActive: false,
            isShareModalActive: false,
            name: null,
            author: null,
            slug: null,
            versions: [],
            caption: null,
            description: null,
            mediaApi: new MediaApi(this.$buefy),
            Internationalize
        }
    },
    computed: {
        variants() {
            return this.item.variants.concat([
                {
                    filename: this.item.filename,
                    width: 'Full size'
                }
            ]);
        },
        externalLink() {
            return window.location.origin + '/media/' + this.item.fullPath;
        },
        directoryPath() {
            return getDirectoryPathString(this.item.parentDirectory);
        },
        directorySlug() {
            return getDirectoryFullSlug(this.item.parentDirectory);
        }
    },
    methods: {
        select(toggle) {
            if(this.item.selected) {
                this.$emit('double-click-action', this.item);
                return;
            }
            this.$emit('select', this.item, toggle);
        },
        openEditModal() {
            this.isEditModalActive = true;
            this.name = this.item.name;
            this.author = this.item.author;
            this.slug = this.item.slug;
            this.caption = this.item.caption;
            this.description = this.item.description;
            this.fetchVersions();
        },
        async fetchVersions() {
            this.versions = [];
            this.versions = (await this.mediaApi.listVersions(this.item.id)).items;
        },
        async saveEdits() {
            let data = await this.mediaApi.update({
                id: this.item.id,
                name: this.name,
                author: this.author,
                slug: this.slug,
                caption: this.caption,
                description: this.description
            });
            this.$buefy.toast.open(morphToNotification(data));
            this.isEditModalActive = false;
            this.$emit('update:item', data.item);
        },
        async restoreItem() {
            await this.mediaApi.restoreAndNotify(this.item.id);
            this.$emit('update:item', this.item);
        },
        async confirmForceDeleteItem() {
            await this.mediaApi.confirmForceDelete(this.item.id);
            this.$emit('update:item', null);
        },
        async deleteItem() {
            await this.mediaApi.deleteAndNotify(this.item.id);
            this.$emit('update:item', this.item);
        },
        async restoreVersion(id) {
            let data = await this.mediaApi.makeHeadVersion(id);
            this.$buefy.toast.open(morphToNotification(data));
            this.versions = [];
            this.isEditModalActive = false;
        },
        async moveToDirectory(directory) {
            console.log('move to directory', directory);
            let data = await this.mediaApi.update({
                id: this.item.id,
                parentDirectory: directory
            });
            this.$buefy.toast.open(morphToNotification(data));
            this.$emit('update:item', this.item);
        }
    }
}
</script>

<style scoped lang="scss">
    @import './media.scss';
</style>
