import { library } from '@fortawesome/fontawesome-svg-core';

// internal icons
import {
    faCheck,
    faCheckCircle,
    faInfoCircle,
    faExternalLinkAlt,
    faExclamationTriangle,
    faExclamationCircle,
    faArrowUp,
    faAngleRight,
    faAngleLeft,
    faAngleDown,
    faEye,
    faEyeSlash,
    faCaretDown,
    faCaretUp,
    faUpload,
    faPlus,
    faCogs,
    faPuzzlePiece,
    faPhotoVideo,
    faUserPlus,
    faMailBulk,
    faUsers,
    faArrowLeft,
    faRecycle,
    faList,
    faFileAlt,
    faFile,
    faFileAudio,
    faFileImage,
    faFilePdf,
    faUserAlt,
    faStamp,
    faCalendarAlt,
    faAddressCard,
    faFileImport,
    faUser,
    faFileExport,
    faDownload,
    faFileExcel,
    faFileCsv,
    faChevronCircleDown,
    faChevronCircleUp,
    faTrash,
    faSearch,
    faBan,
    faShare,
    faTicketAlt,
    faPencilAlt,
    faRedoAlt,
    faTags,
    faLock,
    faUserSlash,
    faUsersCog,
    faMusic,
    faCalendarDay,
    faTimesCircle,
    faEnvelope,
    faUserCog,
    faFolder,
    faHome,
    faSignInAlt,
    faUserEdit,
    faSignOutAlt,
    faTag,
    faFolderPlus,
    faTimes,
    faQuestionCircle,
    faFileUpload,
    faLandmark,
    faFolderOpen,
    faImages,
    faMinusCircle,
    faCalendarPlus, faPaperPlane, faLink, faHandshakeSlash, faHandshake
} from "@fortawesome/free-solid-svg-icons";

export const addIconsToLibrary = () => {
    library.add(faCheck, faLock, faUserSlash, faUserEdit, faUsersCog, faMinusCircle, faSignInAlt,
        faCheckCircle, faInfoCircle, faExclamationTriangle, faExclamationCircle, faFileAlt,
        faArrowUp, faAngleRight, faEnvelope, faAngleLeft, faTicketAlt, faUserCog, faTags, faCalendarDay, faTimesCircle,
        faMusic, faPencilAlt, faRedoAlt, faBan, faExternalLinkAlt,
        faSearch, faAngleDown, faUserAlt, faCogs, faPhotoVideo, faPuzzlePiece, faPlus, faUserPlus, faMailBulk, faUsers,
        faArrowLeft, faRecycle, faList, faStamp, faCalendarAlt, faAddressCard, faFileImport, faFileExport, faDownload,
        faFileExcel, faFileCsv, faChevronCircleDown, faChevronCircleUp, faTrash,
        faEye, faEyeSlash, faCaretDown, faCaretUp, faUpload, faUser, faFolder, faHome, faFilePdf, faSignOutAlt, faTag,
        faFolderPlus, faTimes, faQuestionCircle, faFileUpload, faLandmark,
        faFolderOpen, faFile, faFileAudio, faFileImage, faShare, faImages, faCalendarPlus, faPaperPlane, faHandshake, faHandshakeSlash);
};
